version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: dailyuse-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: dailyuse_test
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data:rw
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d dailyuse_test']
      interval: 5s
      timeout: 5s
      retries: 5
    command: 
      - "postgres"
      - "-c"
      - "fsync=off"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "full_page_writes=off"
