packages:
  - packages/*
  - apps/*
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@swc/core': false
  argon2: true
  better-sqlite3: true
  dtrace-provider: false
  electron: true
  electron-winstaller: false
  esbuild: true
  maplibre-gl: false
  msw: true
  nx: false
  prisma: false
  unrs-resolver: false
  vue-demi: false
nodeLinker: hoisted

onlyBuiltDependencies:
  - argon2
  - electron
