#!/bin/bash
echo "🔍 测试 Goal 数据流"
echo "===================="
echo ""
echo "1. 检查 localStorage 中的 goal-store:"
echo "打开浏览器控制台，运行："
echo "  JSON.parse(localStorage.getItem('goal-store'))"
echo ""
echo "2. 检查 store 中的数据:"
echo "打开浏览器控制台，运行："
echo "  useGoalStore().goals"
echo "  useGoalStore().goals[0].keyResults"
echo ""
echo "3. 清除 localStorage 并重新加载:"
echo "  localStorage.removeItem('goal-store')"
echo "  location.reload()"
echo ""
echo "4. 查看控制台日志，关注："
echo "  - [GoalManagementApplicationService] API 响应"
echo "  - [GoalStore.setGoals] 接收到的 goals"
echo "  - [GoalStore] 序列化/反序列化"
