export const TaskChannels = {
  TEMPLATE_LIST: 'task:template:list',
  TEMPLATE_GET: 'task:template:get',
  TEMPLATE_GRAPH: 'task:template:graph',
  TEMPLATE_CREATE: 'task:template:create',
  TEMPLATE_UPDATE: 'task:template:update',
  TEMPLATE_DELETE: 'task:template:delete',
  TEMPLATE_ARCHIVE: 'task:template:archive',
  TEMPLATE_RESTORE: 'task:template:restore',
  TEMPLATE_PAUSE: 'task:template:pause',
  TEMPLATE_GENERATE_INSTANCES: 'task:template:generate-instances',
  TEMPLATE_GET_INSTANCES: 'task:template:get-instances',
  TEMPLATE_GET_BY_PRIORITY: 'task:template:get-by-priority',
  TEMPLATE_BIND_GOAL: 'task:template:bind-goal',
  TEMPLATE_UNBIND_GOAL: 'task:template:unbind-goal',
  INSTANCE_LIST: 'task:instance:list',
  INSTANCE_LIST_BY_DATE_RANGE: 'task:instance:list-by-date-range',
  INSTANCE_GET: 'task:instance:get',
  INSTANCE_CREATE: 'task:instance:create',
  INSTANCE_DELETE: 'task:instance:delete',
  INSTANCE_COMPLETE: 'task:instance:complete',
  INSTANCE_SKIP: 'task:instance:skip',
  INSTANCE_CHECK_EXPIRED: 'task:instance:check-expired',
  DEPENDENCY_CREATE: 'task:dependency:create',
  DEPENDENCY_LIST: 'task:dependency:list',
  DEPENDENCY_DEPENDENTS: 'task:dependency:dependents',
  DEPENDENCY_CHAIN: 'task:dependency:chain',
  DEPENDENCY_VALIDATE: 'task:dependency:validate',
  DEPENDENCY_DELETE: 'task:dependency:delete',
  DEPENDENCY_UPDATE: 'task:dependency:update',
} as const;

export const GoalChannels = {
  LIST: 'goal:list',
  GET: 'goal:get',
  CREATE: 'goal:create',
  UPDATE: 'goal:update',
  DELETE: 'goal:delete',
  ARCHIVE: 'goal:archive',
  ACTIVATE: 'goal:activate',
  COMPLETE: 'goal:complete',
  SEARCH: 'goal:search',
  AGGREGATE: 'goal:aggregate',
  CLONE: 'goal:clone',
  PROGRESS_BREAKDOWN: 'goal:progressBreakdown',
  FOCUS_MODE_GET: 'goal:focus-mode:get',
  FOCUS_MODE_ACTIVATE: 'goal:focus-mode:activate',
  FOCUS_MODE_DEACTIVATE: 'goal:focus-mode:deactivate',
  FOCUS_MODE_EXTEND: 'goal:focus-mode:extend',
  KEY_RESULT_ADD: 'goal:keyResult:add',
  KEY_RESULT_LIST: 'goal:keyResult:list',
  KEY_RESULT_UPDATE: 'goal:keyResult:update',
  KEY_RESULT_DELETE: 'goal:keyResult:delete',
  KEY_RESULT_BATCH_UPDATE_WEIGHTS: 'goal:keyResult:batchUpdateWeights',
  REVIEW_CREATE: 'goal:review:create',
  REVIEW_LIST: 'goal:review:list',
  REVIEW_UPDATE: 'goal:review:update',
  REVIEW_DELETE: 'goal:review:delete',
  RECORD_CREATE: 'goal:record:create',
  RECORD_LIST_BY_KEY_RESULT: 'goal:record:listByKeyResult',
  RECORD_LIST_BY_GOAL: 'goal:record:listByGoal',
  RECORD_DELETE: 'goal:record:delete',
  FOLDER_LIST: 'goal:folder:list',
  FOLDER_GET: 'goal:folder:get',
  FOLDER_CREATE: 'goal:folder:create',
  FOLDER_UPDATE: 'goal:folder:update',
  FOLDER_DELETE: 'goal:folder:delete',
} as const;

export const ScheduleChannels = {
  LIST: 'schedule:list',
  LIST_BY_DATE_RANGE: 'schedule:list-by-date-range',
  GET: 'schedule:get',
  CREATE: 'schedule:create',
  UPDATE: 'schedule:update',
  DELETE: 'schedule:delete',
  GET_CONFLICTS: 'schedule:get-conflicts',
  DETECT_CONFLICTS: 'schedule:detect-conflicts',
  CREATE_WITH_CONFLICT_DETECTION: 'schedule:create-with-conflict-detection',
  RESOLVE_CONFLICT: 'schedule:resolve-conflict',
  TASK_CREATE: 'schedule:task:create',
  TASK_CREATE_BATCH: 'schedule:task:create-batch',
  TASK_LIST: 'schedule:task:list',
  TASK_GET_BY_ID: 'schedule:task:get-by-id',
  TASK_GET_DUE: 'schedule:task:get-due',
  TASK_GET_BY_SOURCE: 'schedule:task:get-by-source',
  TASK_PAUSE: 'schedule:task:pause',
  TASK_RESUME: 'schedule:task:resume',
  TASK_COMPLETE: 'schedule:task:complete',
  TASK_CANCEL: 'schedule:task:cancel',
  TASK_DELETE: 'schedule:task:delete',
  TASK_DELETE_BATCH: 'schedule:task:delete-batch',
  TASK_UPDATE_METADATA: 'schedule:task:update-metadata',
} as const;

export const ReminderChannels = {
  TEMPLATE_LIST: 'reminder:template:list',
  TEMPLATE_GET: 'reminder:template:get',
  TEMPLATE_CREATE: 'reminder:template:create',
  TEMPLATE_UPDATE: 'reminder:template:update',
  TEMPLATE_DELETE: 'reminder:template:delete',
  TEMPLATE_TOGGLE_ENABLED: 'reminder:template:toggle-enabled',
  TEMPLATE_MOVE_TO_GROUP: 'reminder:template:move-to-group',
  TEMPLATE_GET_BY_USER: 'reminder:template:get-by-user',
  UPCOMING_GET: 'reminder:upcoming:get',
  TODAY_SCHEDULE_GET: 'reminder:today-schedule:get',
  GROUP_LIST: 'reminder:group:list',
  GROUP_GET: 'reminder:group:get',
  GROUP_CREATE: 'reminder:group:create',
  GROUP_UPDATE: 'reminder:group:update',
  GROUP_DELETE: 'reminder:group:delete',
  GROUP_GET_BY_USER: 'reminder:group:get-by-user',
  GROUP_TOGGLE_STATUS: 'reminder:group:toggle-status',
  GROUP_SWITCH_CONTROL_MODE: 'reminder:group:switch-control-mode',
  PREFERENCES_GET: 'reminder:preferences:get',
  PREFERENCES_UPDATE: 'reminder:preferences:update',
} as const;

export const DashboardChannels = {
  GET_STATS: 'dashboard:get-stats',
} as const;

export const AccountChannels = {
  LIST: 'account:list',
  GET: 'account:get',
  GET_CURRENT: 'account:current',
  GET_ME: 'account:get-me',
  UPDATE_PROFILE: 'account:update-profile',
  UPDATE_SETTINGS: 'account:update-settings',
  CHECK_AVAILABILITY: 'account:check-availability',
  CLOSE: 'account:close',
} as const;

export const AuthChannels = {
  LOGIN: 'auth:login',
  REGISTER: 'auth:register',
  LOGOUT: 'auth:logout',
  REFRESH_TOKEN: 'auth:refresh-token',
  ENTER_GUEST_MODE: 'auth:enter-guest-mode',
  GET_CURRENT_USER: 'auth:get-current-user',
  GET_STATUS: 'auth:get-status',
  GET_BOOTSTRAP_SNAPSHOT: 'auth:get-bootstrap-snapshot',
  INITIALIZE: 'auth:initialize',
  AUTO_LOGIN: 'auth:auto-login',
  REMEMBERED_ACCOUNTS_LIST: 'auth:remembered-accounts:list',
  REMEMBERED_ACCOUNTS_REMOVE: 'auth:remembered-accounts:remove',
  VERIFY_TOKEN: 'auth:verify-token',
  TOKEN_STATUS: 'auth:token-status',
  SESSION_STATUS: 'auth:session-status',
  CLEANUP_SESSIONS: 'auth:cleanup-sessions',
  TWO_FACTOR_ENABLE: 'auth:2fa:enable',
  TWO_FACTOR_DISABLE: 'auth:2fa:disable',
  TWO_FACTOR_VERIFY: 'auth:2fa:verify',
  TWO_FACTOR_STATUS: 'auth:2fa:get-status',
  TWO_FACTOR_BACKUP_CODES: 'auth:2fa:generate-backup-codes',
  API_KEY_CREATE: 'auth:api-key:create',
  API_KEY_LIST: 'auth:api-key:list',
  API_KEY_REVOKE: 'auth:api-key:revoke',
  API_KEY_ROTATE: 'auth:api-key:rotate',
  SESSION_LIST: 'auth:session:list',
  SESSION_GET_CURRENT: 'auth:session:get-current',
  SESSION_REVOKE: 'auth:session:revoke',
  SESSION_REVOKE_ALL: 'auth:session:revoke-all',
  DEVICE_LIST: 'auth:device:list',
  DEVICE_GET_CURRENT: 'auth:device:get-current',
  DEVICE_TRUST: 'auth:device:trust',
  DEVICE_REVOKE: 'auth:device:revoke',
  DEVICE_RENAME: 'auth:device:rename',
  FORGOT_PASSWORD: 'auth:forgot-password',
  RESET_PASSWORD: 'auth:reset-password',
  CHANGE_PASSWORD: 'auth:change-password',
  SEND_SMS_CODE: 'auth:send-sms-code',
} as const;

export const AIChannels = {
  CAPABILITIES_GET: 'ai:capabilities:get',
  PROVIDER_CREATE: 'ai:provider:create',
  PROVIDER_LIST: 'ai:provider:list',
  PROVIDER_GET: 'ai:provider:get',
  PROVIDER_UPDATE: 'ai:provider:update',
  PROVIDER_DELETE: 'ai:provider:delete',
  PROVIDER_TEST: 'ai:provider:test',
  PROVIDER_SET_DEFAULT: 'ai:provider:set-default',
  PROVIDER_REFRESH_MODELS: 'ai:provider:refresh-models',
  GOAL_GENERATE: 'ai:goal:generate',
  CONVERSATION_CREATE: 'ai:chat:conversation:create',
  CONVERSATION_UPDATE: 'ai:chat:conversation:update',
  CONVERSATION_LIST: 'ai:chat:conversation:list',
  CONVERSATION_GET: 'ai:chat:conversation:get',
  CONVERSATION_DELETE: 'ai:chat:conversation:delete',
  MESSAGE_SEND: 'ai:chat:message:send',
  MESSAGE_LIST: 'ai:chat:message:list',
  MESSAGE_STREAM_START: 'ai:chat:message:stream:start',
  MESSAGE_STREAM_CANCEL: 'ai:chat:message:stream:cancel',
  KNOWLEDGE_EXPAND: 'ai:knowledge:expand',
  KNOWLEDGE_QUERY: 'ai:knowledge:query',
  KNOWLEDGE_REINDEX: 'ai:knowledge:reindex',
  KNOWLEDGE_NOTE_CREATE: 'ai:knowledge-note:create',
  ANALYTICS_QUERY: 'ai:analytics:query',
  EVALUATION_OVERVIEW_GET: 'ai:evaluations:overview:get',
} as const;

export const AIStreamChannels = {
  MESSAGE_STREAM_CHUNK: 'ai:chat:message:stream:chunk',
  MESSAGE_STREAM_DONE: 'ai:chat:message:stream:done',
  MESSAGE_STREAM_ERROR: 'ai:chat:message:stream:error',
} as const;

export const NotificationChannels = {
  LIST: 'notification:list',
  GET: 'notification:get',
  CREATE: 'notification:create',
  MARK_READ: 'notification:mark-read',
  MARK_ALL_READ: 'notification:mark-all-read',
  DELETE: 'notification:delete',
  CLEAR_ALL: 'notification:clear-all',
  GET_UNREAD_COUNT: 'notification:unread-count',
  CUSTOM_RECEIVE: 'notification:custom:receive',
  CUSTOM_CLICK: 'notification:custom:click',
  CUSTOM_CLOSE: 'notification:custom:close',
  CUSTOM_RESIZE: 'notification:custom:resize',
  CUSTOM_MOUSE_ENTER: 'notification:custom:mouse-enter',
  CUSTOM_MOUSE_LEAVE: 'notification:custom:mouse-leave',
  CUSTOM_RENDERER_READY: 'notification:custom:renderer-ready',
} as const;

export const RepositoryChannels = {
  CURRENT: 'repository:current',
  RESOURCE_LIST: 'repository:resource:list',
  RESOURCE_GET: 'repository:resource:get',
  RESOURCE_CREATE: 'repository:resource:create',
  RESOURCE_UPLOAD: 'repository:resource:upload',
  RESOURCE_UPDATE: 'repository:resource:update',
  RESOURCE_DELETE: 'repository:resource:delete',
  BOOKMARK_LIST: 'repository:bookmark:list',
  BOOKMARK_CREATE: 'repository:bookmark:create',
  BOOKMARK_UPDATE: 'repository:bookmark:update',
  BOOKMARK_REORDER: 'repository:bookmark:reorder',
  BOOKMARK_DELETE: 'repository:bookmark:delete',
  FOLDER_LIST: 'repository:folder:list',
  FOLDER_CREATE: 'repository:folder:create',
  FOLDER_UPDATE: 'repository:folder:update',
  FOLDER_DELETE: 'repository:folder:delete',
  SEARCH: 'repository:search',
} as const;

export const SettingChannels = {
  GET_ALL: 'setting:all',
  PATCH: 'setting:patch',
  RESET: 'setting:reset',
  IMPORT: 'setting:import',
  EXPORT: 'setting:export',
} as const;

export const EditorChannels = {
  WORKSPACE_LIST: 'editor:list-workspaces',
  WORKSPACE_GET: 'editor:get-workspace',
  WORKSPACE_CREATE: 'editor:create-workspace',
  WORKSPACE_UPDATE: 'editor:update-workspace',
  WORKSPACE_DELETE: 'editor:delete-workspace',
  SESSION_LIST: 'editor:list-sessions',
  SESSION_GET: 'editor:get-session',
  SESSION_CREATE: 'editor:create-session',
  SESSION_UPDATE: 'editor:update-session',
  SESSION_ACTIVATE: 'editor:activate-session',
  SESSION_DELETE: 'editor:delete-session',
  GROUP_CREATE: 'editor:create-group',
  GROUP_UPDATE: 'editor:update-group',
  GROUP_DELETE: 'editor:delete-group',
  TAB_CREATE: 'editor:create-tab',
  TAB_UPDATE: 'editor:update-tab',
  TAB_ACTIVATE: 'editor:activate-tab',
  TAB_DELETE: 'editor:delete-tab',
  GET_CONTENT: 'editor:get-content',
  SAVE_CONTENT: 'editor:save-content',
  AUTO_SAVE: 'editor:auto-save-content',
  SEARCH: 'editor:search-resources',
} as const;

export const GovernanceChannels = {
  RULE_LIST: 'governance:rule:list',
  RULE_GET: 'governance:rule:get',
  RULE_SEARCH: 'governance:rule:search',
  RULE_CREATE: 'governance:rule:create',
  RULE_UPDATE: 'governance:rule:update',
  RULE_DELETE: 'governance:rule:delete',
  RULE_REVISIONS: 'governance:rule-revision:list',
} as const;

export const SystemChannels = {
  GET_APP_VERSION: 'system:getAppVersion',
  GET_LAZY_MODULE_STATS: 'system:getLazyModuleStats',
  GET_MEMORY_USAGE: 'system:getMemoryUsage',
  GET_IPC_CACHE_STATS: 'system:getIpcCacheStats',
} as const;

export const DesktopFeatureChannels = {
  AUTO_LAUNCH_IS_ENABLED: 'desktop:autoLaunch:isEnabled',
  AUTO_LAUNCH_ENABLE: 'desktop:autoLaunch:enable',
  AUTO_LAUNCH_DISABLE: 'desktop:autoLaunch:disable',
  SHORTCUTS_GET_ALL: 'desktop:shortcuts:getAll',
  SHORTCUTS_UPDATE: 'desktop:shortcuts:update',
  TRAY_FLASH: 'desktop:tray:flash',
  TRAY_STOP_FLASH: 'desktop:tray:stopFlash',
} as const;

export const RendererEventChannels = {
  TRAY_ACTION: 'tray:action',
  SHORTCUT_TRIGGERED: 'shortcut:triggered',
  DB_CHANGED: 'db:changed',
  WINDOW_STATE_CHANGED: 'window-state:changed',
} as const;

export const CacheChannels = {
  STATS: 'cache:stats',
  CLEAR: 'cache:clear',
  INVALIDATE: 'cache:invalidate',
} as const;

export const DevChannels = {
  MEMORY_STATUS: 'dev:memory:status',
  MEMORY_SNAPSHOTS: 'dev:memory:snapshots',
  MEMORY_FORCE_GC: 'dev:memory:force-gc',
} as const;

export const WindowChannels = {
  TRANSITION_TO_MAIN: 'window:transition-to-main',
  TRANSITION_TO_LOGIN: 'window:transition-to-login',
  GET_TYPE: 'window:get-type',
  SYNC_CHROME_THEME: 'window:sync-chrome-theme',
  MINIMIZE: 'window:minimize',
  TOGGLE_MAXIMIZE: 'window:toggle-maximize',
  CLOSE: 'window:close',
  GET_CONTROLS_STATE: 'window:get-controls-state',
} as const;
