"""Enhanced LangGraph for the knowledge.generate Agent with real search integration."""

from __future__ import annotations

import time
from collections.abc import Callable
from typing import Any, TypedDict, cast

from langgraph.graph import END, START, StateGraph
from langgraph.types import interrupt

from ai_service.agent_runtime.events import (
    append_agent_event,
    append_node_lifecycle_events,
    append_tool_lifecycle_events,
)
from ai_service.schemas import (
    AgentAction,
    AgentArtifact,
    AgentMessage,
    AgentResumePayload,
    IndexedKnowledgeResource,
    ProviderConfig,
)

Clock = Callable[[], int]
GraphUpdate = dict[str, Any]


class KnowledgeGenerateGraphState(TypedDict, total=False):
    """Serializable state used by the experimental knowledge.generate graph."""

    run_id: str
    thread_id: str
    conversation_id: str | None
    identity_id: str
    created_at: int
    updated_at: int
    status: str
    intent: str | None
    stage: str
    topic: str
    title: str | None
    source: str | None
    target_subpath: str | None
    provider_id: str | None
    model: str | None
    provider_config: dict[str, Any] | None
    indexed_resources: list[dict[str, Any]]
    approval_interrupt: dict[str, Any]
    execution_interrupt: dict[str, Any]
    messages: list[dict[str, Any]]
    artifacts: list[dict[str, Any]]
    citations: list[dict[str, Any]]
    retrieved_context: list[dict[str, Any]]
    pending_actions: list[dict[str, Any]]
    approved_actions: list[dict[str, Any]]
    executed_actions: list[dict[str, Any]]
    usage: dict[str, Any]
    errors: list[str]
    events: list[dict[str, Any]]


def _required(state: KnowledgeGenerateGraphState, key: str) -> Any:
    return cast(dict[str, Any], state)[key]


def _run_id(state: KnowledgeGenerateGraphState) -> str:
    return str(_required(state, "run_id"))


def _topic(state: KnowledgeGenerateGraphState) -> str:
    return str(_required(state, "topic"))


def _thread_id(state: KnowledgeGenerateGraphState) -> str:
    return str(_required(state, "thread_id"))


def _default_clock_ms() -> int:
    return int(time.time() * 1000)


def _compact_text(value: str) -> str:
    return " ".join(value.strip().split())


def _note_title(topic: str, title: str | None) -> str:
    candidate = _compact_text(title or topic)
    if len(candidate) > 80:
        return f"{candidate[:77].rstrip()}..."
    return candidate or "Untitled knowledge note"


def _note_markdown(*, topic: str, title: str, source: str | None) -> str:
    lines = [
        f"# {title}",
        "",
        "## Topic",
        topic,
        "",
        "## Draft",
        (
            "This note draft was generated by the experimental "
            "knowledge.generate graph. Review it before saving."
        ),
    ]
    if source:
        lines.extend(["", "## Source", source.strip()])
    return "\n".join(lines).strip()


def _save_plan(
    *,
    artifact_id: str,
    title: str,
    topic: str,
    markdown: str,
    target_subpath: str | None,
    tags: list[str],
    provider_id: str | None,
    model: str | None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "title": title,
        "topic": topic,
        "contentMarkdown": markdown,
        "contentArtifactId": artifact_id,
        "tags": tags,
    }
    if target_subpath:
        payload["targetSubpath"] = target_subpath
    if provider_id:
        payload["providerId"] = provider_id
    if model:
        payload["model"] = model

    return {
        "summary": "Save this reviewed draft as a repository knowledge note.",
        "confirmationRequired": True,
        "pendingAction": {
            "tool": "create_knowledge_note",
            "payload": payload,
            "rationale": (
                "Persist the approved knowledge note draft through the "
                "controlled Repository executor."
            ),
            "index": 0,
            "dependsOn": [],
        },
        "postSave": {"indexStatus": "pending"},
    }


def _execution_summary(executed_actions: list[dict[str, Any]]) -> dict[str, Any]:
    executed_count = sum(
        1 for action in executed_actions if action.get("status") == "executed"
    )
    failed_count = sum(
        1 for action in executed_actions if action.get("status") == "failed"
    )
    return {
        "status": "success" if failed_count == 0 else "failed",
        "executedCount": executed_count,
        "failedCount": failed_count,
    }


def _execution_recovery(
    *,
    executed_actions: list[dict[str, Any]],
    approved_actions: list[dict[str, Any]],
) -> dict[str, Any]:
    failed_actions = [
        action for action in executed_actions if action.get("status") == "failed"
    ]
    suggestions = []
    if failed_actions:
        suggestions.append(
            "Review the knowledge note save error and retry the same approved "
            "draft after fixing the repository or payload issue."
        )

    return {
        "canRetry": bool(failed_actions),
        "failedActions": failed_actions,
        "skippedActions": [],
        "suggestions": suggestions,
        "retryApprovedActions": approved_actions,
    }


def _node_event(
    state: KnowledgeGenerateGraphState,
    node: str,
    clock: Clock,
    *,
    started_at: int | None = None,
) -> list[dict[str, Any]]:
    started_at = started_at if started_at is not None else clock()
    return append_node_lifecycle_events(
        state.get("events", []),
        run_id=_run_id(state),
        node=node,
        created_at=started_at,
        completed_at=clock(),
    )


def create_knowledge_generate_initial_state(
    *,
    run_id: str,
    thread_id: str,
    identity_id: str,
    topic: str,
    conversation_id: str | None = None,
    title: str | None = None,
    source: str | None = None,
    target_subpath: str | None = None,
    provider_id: str | None = None,
    model: str | None = None,
    provider_config: ProviderConfig | None = None,
    indexed_resources: list[IndexedKnowledgeResource] | None = None,
    clock: Clock = _default_clock_ms,
) -> KnowledgeGenerateGraphState:
    """Build the initial state for one knowledge.generate Agent run."""

    now = clock()
    user_message = AgentMessage(
        role="user",
        content=source or topic,
        createdAt=now,
    )
    return {
        "run_id": run_id,
        "thread_id": thread_id,
        "conversation_id": conversation_id,
        "identity_id": identity_id,
        "created_at": now,
        "updated_at": now,
        "status": "pending",
        "intent": "knowledge-generate",
        "stage": "intake",
        "topic": topic,
        "title": title,
        "source": source,
        "target_subpath": target_subpath,
        "provider_id": provider_id,
        "model": model,
        "provider_config": (
            provider_config.model_dump(by_alias=True, exclude_none=True)
            if provider_config
            else None
        ),
        "indexed_resources": (
            [
                resource.model_dump(by_alias=True, exclude_none=True)
                for resource in indexed_resources
            ]
            if indexed_resources
            else []
        ),
        "messages": [user_message.model_dump(by_alias=True, exclude_none=True)],
        "artifacts": [],
        "citations": [],
        "retrieved_context": [],
        "pending_actions": [],
        "approved_actions": [],
        "executed_actions": [],
        "usage": {},
        "errors": [],
        "events": [],
    }


def build_knowledge_generate_graph(
    *,
    clock: Clock = _default_clock_ms,
    knowledge_note_generator: Any | None = None,
    knowledge_citation_selector: Any | None = None,
) -> Any:
    """Compile an enhanced knowledge.generate graph with real search integration.

    Args:
        clock: Clock function for timestamps
        knowledge_note_generator: Optional callable(topic, title, provider_config)
            that returns a dict with 'content' and 'usage' keys. If provided,
            draft_note will use provider-backed generation instead of templates.
        knowledge_citation_selector: Optional callable(question, indexed_resources,
            provider_config, max_citations) that returns list of similar citations.
            If provided, retrieve_context will use real knowledge base search.
    """

    def intake(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        started_at = clock()
        events = append_agent_event(
            state.get("events", []),
            run_id=_run_id(state),
            event_type="run.started",
            created_at=started_at,
            data={"agentType": "knowledge.generate"},
        )
        return {
            "status": "running",
            "stage": "intake",
            "updated_at": clock(),
            "events": append_node_lifecycle_events(
                events,
                run_id=_run_id(state),
                node="intake",
                created_at=started_at,
                completed_at=clock(),
            ),
        }

    def retrieve_context(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        started_at = clock()
        topic = _topic(state)
        indexed_resources_data = state.get("indexed_resources", [])
        matches: list[dict[str, Any]] = []
        match_count = 0

        # Try real knowledge search if available
        if (
            knowledge_citation_selector is not None
            and indexed_resources_data
            and state.get("provider_config")
        ):
            try:
                indexed_resources = [
                    IndexedKnowledgeResource.model_validate(resource)
                    for resource in indexed_resources_data
                ]
                provider_config = ProviderConfig.model_validate(
                    state.get("provider_config")
                )
                citations = knowledge_citation_selector(
                    question=topic,
                    indexed_resources=indexed_resources,
                    provider_config=provider_config,
                    max_citations=10,  # Get more matches for duplicate risk assessment
                )
                matches = [
                    {
                        "resourceId": citation.resource_id,
                        "resourcePath": citation.resource_path,
                        "title": citation.title,
                        "chunkIndex": citation.chunk_index,
                        "excerpt": citation.excerpt,
                        "score": citation.score,
                    }
                    for citation in citations
                ]
                match_count = len(matches)
            except Exception:
                # Fallback to empty matches on error
                matches = []
                match_count = 0

        completed_at = clock()
        return {
            "stage": "retrieve_context",
            "updated_at": completed_at,
            "retrieved_context": [
                {
                    "tool": "find_related_notes",
                    "query": topic,
                    "matches": matches,
                    "matchCount": match_count,
                }
            ],
            "events": append_tool_lifecycle_events(
                append_node_lifecycle_events(
                    state.get("events", []),
                    run_id=_run_id(state),
                    node="retrieve_context",
                    created_at=started_at,
                    completed_at=completed_at,
                ),
                run_id=_run_id(state),
                tool="find_related_notes",
                created_at=started_at,
                completed_at=completed_at,
                started_data={"query": topic},
                completed_data={
                    "status": "completed",
                    "query": topic,
                    "matchCount": match_count,
                },
            ),
        }

    def draft_note(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        now = clock()
        title = _note_title(_topic(state), state.get("title"))
        source = state.get("source")
        tags: list[str] = []
        artifact_id = f"{_run_id(state)}:knowledge-note-draft"
        usage: dict[str, Any] = {}

        # Try provider-backed generation if available
        if knowledge_note_generator is not None:
            provider_config_data = state.get("provider_config")
            provider_config = (
                ProviderConfig.model_validate(provider_config_data)
                if provider_config_data
                else None
            )

            try:
                response = knowledge_note_generator(
                    topic=_topic(state),
                    title=title,
                    provider_config=provider_config,
                )
                markdown = response.get("content", "")
                usage = response.get("usage", {})

                # Fallback to template if generation returned empty
                if not markdown or len(markdown.strip()) < 50:
                    markdown = _note_markdown(
                        topic=_topic(state),
                        title=title,
                        source=source,
                    )
            except Exception:
                # Fallback to template on any error
                markdown = _note_markdown(
                    topic=_topic(state),
                    title=title,
                    source=source,
                )
        else:
            # No generator provided, use template
            markdown = _note_markdown(
                topic=_topic(state),
                title=title,
                source=source,
            )

        # Detect duplicate risk based on retrieved context
        retrieved_context = state.get("retrieved_context", [])
        duplicate_risk = "unknown"
        related_notes: list[dict[str, Any]] = []

        for ctx in retrieved_context:
            if ctx.get("tool") == "find_related_notes":
                match_count = ctx.get("matchCount", 0)
                matches = ctx.get("matches", [])

                # Assess duplicate risk based on match count and scores
                if match_count == 0:
                    duplicate_risk = "none"
                elif match_count >= 5:
                    # Check if there are high-score matches
                    high_score_count = sum(
                        1 for match in matches if match.get("score", 0) >= 3.0
                    )
                    duplicate_risk = "high" if high_score_count >= 2 else "medium"
                elif match_count >= 2:
                    duplicate_risk = "low"
                else:
                    duplicate_risk = "low"

                # Extract related notes info
                related_notes = [
                    {
                        "resourcePath": match.get("resourcePath"),
                        "title": match.get("title"),
                        "score": match.get("score"),
                        "excerpt": match.get("excerpt"),
                    }
                    for match in matches[:5]  # Top 5 related notes
                ]
                break

        save_plan = _save_plan(
            artifact_id=artifact_id,
            title=title,
            topic=_topic(state),
            markdown=markdown,
            target_subpath=state.get("target_subpath"),
            tags=tags,
            provider_id=state.get("provider_id"),
            model=state.get("model"),
        )
        artifact_data = {
            "topic": _topic(state),
            "title": title,
            "markdown": markdown,
            "source": source,
            "targetSubpath": state.get("target_subpath"),
            "tags": tags,
            "duplicateRisk": duplicate_risk,
            "relatedNotes": related_notes,
            "indexStatus": "draft",
            "savePlan": save_plan,
        }
        artifact = AgentArtifact(
            artifactId=artifact_id,
            kind="knowledge_note_draft",
            title=title,
            data=artifact_data,
            updatedAt=now,
        )
        events = append_agent_event(
            _node_event(state, "draft_note", clock),
            run_id=_run_id(state),
            event_type="artifact.updated",
            created_at=now,
            data={"artifactId": artifact.artifact_id, "kind": artifact.kind},
        )
        return {
            "stage": "draft_note",
            "status": "running",
            "updated_at": now,
            "artifacts": [artifact.model_dump(by_alias=True)],
            "pending_actions": [save_plan["pendingAction"]],
            "usage": usage,
            "events": events,
        }

    def prepare_approval(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        now = clock()
        approval_payload = {
            "runId": _run_id(state),
            "threadId": _thread_id(state),
            "agentType": "knowledge.generate",
            "pendingActions": state.get("pending_actions", []),
            "artifacts": state.get("artifacts", []),
        }
        return {
            "stage": "approval",
            "status": "waiting_approval",
            "updated_at": now,
            "approval_interrupt": approval_payload,
            "events": append_agent_event(
                _node_event(state, "prepare_approval", clock),
                run_id=_run_id(state),
                event_type="approval.required",
                created_at=now,
                data=approval_payload,
            ),
        }

    def approval_interrupt(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        resume_value = interrupt(_required(state, "approval_interrupt"))
        payload = AgentResumePayload.model_validate(resume_value)
        if payload.user_decision == "cancel":
            return {
                "stage": "result",
                "status": "cancelled",
                "updated_at": clock(),
                "approved_actions": [],
            }

        if payload.user_decision not in {"confirm", "edit"}:
            raise ValueError(
                "Knowledge Generation approval can only resume with confirm, "
                "edit, or cancel decisions."
            )

        artifacts = state.get("artifacts", [])
        if payload.edited_artifacts is not None:
            artifacts = [
                artifact.model_dump(by_alias=True)
                for artifact in payload.edited_artifacts
            ]

        approved_actions = payload.approved_actions
        if approved_actions is None:
            approved_actions = [
                AgentAction.model_validate(action)
                for action in state.get("pending_actions", [])
            ]

        return {
            "stage": "execute",
            "status": "running",
            "updated_at": clock(),
            "artifacts": artifacts,
            "approved_actions": [
                action.model_dump(by_alias=True) for action in approved_actions
            ],
        }

    def prepare_execution(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        now = clock()
        execution_payload = {
            "type": "execution.required",
            "runId": _run_id(state),
            "threadId": _thread_id(state),
            "agentType": "knowledge.generate",
            "approvedActions": state.get("approved_actions", []),
            "artifacts": state.get("artifacts", []),
        }
        return {
            "stage": "execute",
            "status": "waiting_execution",
            "updated_at": now,
            "execution_interrupt": execution_payload,
            "events": append_agent_event(
                _node_event(state, "prepare_execution", clock),
                run_id=_run_id(state),
                event_type="execution.required",
                created_at=now,
                data=execution_payload,
            ),
        }

    def execution_interrupt(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        resume_value = interrupt(_required(state, "execution_interrupt"))
        payload = AgentResumePayload.model_validate(resume_value)
        if payload.executed_actions is None:
            raise ValueError(
                "Executed actions are required to finish "
                "Knowledge Generation execution."
            )

        executed_actions = [
            action.model_dump(by_alias=True, exclude_none=True)
            for action in payload.executed_actions
        ]
        events = _node_event(state, "execution_interrupt", clock)
        for action in executed_actions:
            events = append_tool_lifecycle_events(
                events,
                run_id=_run_id(state),
                tool=str(action.get("tool")),
                created_at=clock(),
                completed_at=clock(),
                started_data={"source": "external_executor"},
                completed_data={
                    "source": "external_executor",
                    "status": action.get("status"),
                    "message": action.get("message"),
                    "entityId": action.get("entityId"),
                    "data": action.get("data"),
                    "action": action,
                },
            )
            events = append_agent_event(
                events,
                run_id=_run_id(state),
                event_type="action.executed",
                created_at=clock(),
                data=action,
            )
        return {
            "stage": "result",
            "status": "running",
            "updated_at": clock(),
            "executed_actions": executed_actions,
            "events": events,
        }

    def result(state: KnowledgeGenerateGraphState) -> GraphUpdate:
        now = clock()
        executed_actions = state.get("executed_actions", [])
        artifacts = state.get("artifacts", [])
        if executed_actions:
            timeline = AgentArtifact(
                artifactId=f"{_run_id(state)}:knowledge-note-execution",
                kind="execution_timeline",
                title="Knowledge note save result",
                data={
                    "summary": _execution_summary(executed_actions),
                    "executedActions": executed_actions,
                    "recovery": _execution_recovery(
                        executed_actions=executed_actions,
                        approved_actions=state.get("approved_actions", []),
                    ),
                },
                updatedAt=now,
            )
            artifacts = [
                artifact
                for artifact in artifacts
                if artifact.get("kind") != "execution_timeline"
            ]
            artifacts.append(timeline.model_dump(by_alias=True))
        return {
            "stage": "result",
            "status": (
                state.get("status")
                if state.get("status") == "cancelled"
                else "completed"
            ),
            "updated_at": now,
            "artifacts": artifacts,
            "events": append_agent_event(
                _node_event(state, "result", clock),
                run_id=_run_id(state),
                event_type="run.completed",
                created_at=now,
                data={"status": "completed"},
            ),
        }

    graph = StateGraph(KnowledgeGenerateGraphState)
    graph.add_node("intake", intake)
    graph.add_node("retrieve_context", retrieve_context)
    graph.add_node("draft_note", draft_note)
    graph.add_node("prepare_approval", prepare_approval)
    graph.add_node("approval_interrupt", approval_interrupt)
    graph.add_node("prepare_execution", prepare_execution)
    graph.add_node("execution_interrupt", execution_interrupt)
    graph.add_node("result", result)

    graph.add_edge(START, "intake")
    graph.add_edge("intake", "retrieve_context")
    graph.add_edge("retrieve_context", "draft_note")
    graph.add_edge("draft_note", "prepare_approval")
    graph.add_edge("prepare_approval", "approval_interrupt")
    graph.add_conditional_edges(
        "approval_interrupt",
        lambda state: (
            "result" if state.get("status") == "cancelled" else "prepare_execution"
        ),
        {
            "result": "result",
            "prepare_execution": "prepare_execution",
        },
    )
    graph.add_edge("prepare_execution", "execution_interrupt")
    graph.add_edge("execution_interrupt", "result")
    graph.add_edge("result", END)
    return graph
