<template>
  <section class="flex h-full min-h-0 flex-col overflow-hidden bg-background" data-testid="task-detail-view">
    <header class="flex min-h-14 items-center gap-2 border-b px-4"><Button variant="ghost" size="sm" @click="router.push({name:'task-list'})"><ArrowLeft class="mr-1 h-4 w-4"/>{{ t('common.back') }}</Button><div v-if="viewModel" class="min-w-0"><h1 class="truncate font-semibold">{{ viewModel.title }}</h1></div><div class="ml-auto flex gap-1"><Button v-if="viewModel" variant="ghost" size="sm" @click="openEdit">{{ t('common.edit') }}</Button><Button v-if="viewModel?.isActive" variant="ghost" size="sm" @click="pause">Pause</Button><Button v-else-if="viewModel && !viewModel.isArchived" variant="ghost" size="sm" @click="activate">Activate</Button><Button v-if="viewModel" variant="ghost" size="sm" @click="archive">Archive</Button><Button v-if="viewModel" variant="ghost" size="sm" class="text-destructive" @click="remove">{{ t('common.delete') }}</Button></div></header>
    <div v-if="isLoading" class="flex flex-1 items-center justify-center text-sm text-muted-foreground">{{ t('common.loading') }}</div>
    <div v-else-if="error" class="m-4 rounded-md border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{{ error }}</div>
    <div v-else-if="viewModel" class="min-h-0 flex-1 overflow-auto p-4"><div class="mx-auto max-w-3xl space-y-4"><article class="rounded-lg border bg-card p-5"><div class="flex flex-wrap items-center gap-2"><Badge>{{ viewModel.statusText }}</Badge><Badge variant="outline">{{ viewModel.importanceText }}</Badge><Badge v-if="viewModel.goalBinding" variant="secondary">Goal linked</Badge></div><p v-if="viewModel.description" class="mt-4 text-sm text-muted-foreground">{{ viewModel.description }}</p><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-muted-foreground">Recurrence</dt><dd>{{ viewModel.recurrenceText }}</dd></div><div><dt class="text-muted-foreground">Progress</dt><dd>{{ viewModel.completedDueInstanceCount ?? 0 }} / {{ viewModel.dueInstanceCount ?? 0 }}</dd></div><div><dt class="text-muted-foreground">Future pending</dt><dd>{{ viewModel.futurePendingInstanceCount ?? 0 }}</dd></div><div><dt class="text-muted-foreground">Created</dt><dd>{{ viewModel.formattedCreatedAt ?? '-' }}</dd></div></dl><div v-if="viewModel.tags?.length" class="mt-4 flex flex-wrap gap-1"><Badge v-for="tag in viewModel.tags" :key="tag" variant="outline">{{ tag }}</Badge></div></article></div></div>
    <TaskTemplateDialog v-model="showEditDialog" mode="edit" :template="viewModel" :saving="isSaving" @save="saveEdit" @cancel="showEditDialog=false" />
  </section>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { ArrowLeft } from '@lucide/vue'; import { Badge, Button } from '@memoflow/ui-vue-shadcn';
import type { GoalId, KeyResultId } from '@memoflow/contracts/primitives'; import { ImportanceLevel } from '@memoflow/contracts/shared'; import { type RecurrenceRuleDTO } from '@memoflow/contracts/task';
import TaskTemplateDialog from '../components/dialogs/TaskTemplateDialog.vue'; import type { TaskTemplateViewModel } from '../components/types'; import { useTaskTemplateDetailQuery } from '../composables/useTaskTemplateDetailQuery'; import { useTaskTemplateMutations } from '../composables/useTaskTemplateMutations'; import { mapTaskTemplateDtoToViewModel,toTaskTimeConfigPayload } from '../utils/task-template-presentation';
const route=useRoute(); const router=useRouter(); const {t}=useI18n(); const id=computed(()=>String(route.params.id??'')); const {currentTemplate,isLoading,error,refetch}=useTaskTemplateDetailQuery(id); const {updateTemplateSafe,activateTemplateSafe,pauseTemplateSafe,archiveTemplateSafe,deleteTemplateSafe,isSaving}=useTaskTemplateMutations(); const viewModel=computed(()=>currentTemplate.value?mapTaskTemplateDtoToViewModel(currentTemplate.value,t):null); const showEditDialog=ref(false); function openEdit(){showEditDialog.value=true;}
function goalBinding(vm:TaskTemplateViewModel){if(!vm.goalBinding?.goalId||!vm.goalBinding.keyResultId)return vm.goalBinding===null?null:undefined;return {goalId:vm.goalBinding.goalId as GoalId,keyResultId:vm.goalBinding.keyResultId as KeyResultId,contribution:vm.goalBinding.contribution??null};}
async function saveEdit(vm:TaskTemplateViewModel){const r=await updateTemplateSafe(id.value,{name:vm.title,description:vm.description??null,timeConfig:toTaskTimeConfigPayload(vm.timeConfig),recurrenceRule:(vm.recurrenceRule as unknown as RecurrenceRuleDTO)??null,importance:(vm.importance as ImportanceLevel)??ImportanceLevel.Moderate,tags:vm.tags??[],color:vm.color??null,goalBinding:goalBinding(vm)});if(r){showEditDialog.value=false;await refetch();}}
async function pause(){if(await pauseTemplateSafe(id.value))await refetch();} async function activate(){if(await activateTemplateSafe(id.value))await refetch();} async function archive(){if(await archiveTemplateSafe(id.value))await refetch();} async function remove(){if(await deleteTemplateSafe(id.value))await router.push({name:'task-list'});}
</script>
